org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=Apotheosis
modName=Apotheosis
modGroup=dev.shadowsoffire
modid=apotheosis
author=Shadows_of_Fire
desc=All things that should have been
version=8.2.2-beta3

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.144
parchmentVersion=2024.07.28-1.21
jeiVersion=19.8.4.113
jadeVersion=15.1.6
curiosVersion=9.3.1+1.21.1
placeboVersion=9.7.1
patchouliVersion=1.21-87-NEOFORGE
#bookshelfVersion=20.0.2
#gamestagesVersion=15.0.1
twilightFileId=5983260
gatewaysVersion=5.0.2
apothicAttributesVersion=2.7.0
apothicSpawnersVersion=1.2.0
apothicEnchantingVersion=1.3.0

# Mixins
mixin=true
mixinVersion=0.8.5

# Publishing
modLoaders=NeoForge
releaseType=release
requiredDeps=apothic-attributes, placebo, patchouli, apothic-enchanting, apothic-spawners
optionalDeps=jei, jade, max-health-fix, enchantment-descriptions
#incompatibleDeps=
curseforgeProjectId=313970

# Tests
enableTests=false
