org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Basic Information
fileName=Apotheosis
modName=Apotheosis
modGroup=dev.shadowsoffire
modid=apotheosis
author=Shadows_of_Fire
desc=All things that should have been
version=9.0.0-beta0
logo=logo_transparent.png
homepage=https://www.curseforge.com/minecraft/mc-mods/apotheosis

# Dependencies
mcVersion=26.1.2
javaVersion=25
forgeVersion=26.1.2.22-beta
jeiVersion=29.5.0.26
jadeVersion=26.0.9
#curiosVersion=9.5.1+1.21.1
placeboVersion=10.0.0-beta7
patchouliVersion=26.1-94-SNAPSHOT
#bookshelfVersion=20.0.2
#gamestagesVersion=15.0.1
#twilightFileId=5983260
gatewaysVersion=6.0.0-beta1
apothicAttributesVersion=3.0.0-beta1
apothicSpawnersVersion=2.0.0beta0
apothicEnchantingVersion=4.0.0-beta5

# Mixins
mixin=true
mixinVersion=0.8.5

# Publishing
modLoaders=NeoForge
releaseType=release
requiredDeps=apothic-attributes, placebo, patchouli, apothic-enchanting, apothic-spawners
optionalDeps=jei, jade, max-health-fix, enchantment-descriptions
#incompatibleDeps=
curseforgeProjectId=313970

# Tests
enableTests=false
