modLoader="javafml"

loaderVersion="[2,)"

license="${license}"

[[mods]] #mandatory

modId="${modid}"

version="${version}"

displayName="${modName}"

authors="${author}"

description='''${desc}'''

logoFile="${logo}"

displayURL="${homepage}"

${mixinConfig}

[[dependencies.${modid}]]
    modId="minecraft"
    type="required"
    versionRange="[26.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.0.1-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="placebo"
    type="required"
    versionRange="[${placeboVersion},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${modid}]]
    modId="apothic_attributes"
    type="required"
    versionRange="[${apothicAttributesVersion},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${modid}]]
    modId="apothic_spawners"
    type="optional"
    versionRange="[${apothicSpawnersVersion},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${modid}]]
    modId="apothic_enchanting"
    type="optional"
    versionRange="[${apothicEnchantingVersion},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${modid}]]
    modId="gateways"
    type="optional"
    versionRange="[${gatewaysVersion},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${modid}]]
    modId="patchouli"
    type="optional"
    versionRange="[${patchouliVersion},)"
    ordering="AFTER"
    side="BOTH"
