modLoader="javafml"

loaderVersion="[2,)"

license="MIT License (code) / All Rights Reserved (assets)"

[[mods]] #mandatory

modId="apotheosis"

version="8.5.2"

displayName="Apotheosis"

authors="Shadows_of_Fire"

description='''All things that should have been'''

logoFile="logo_transparent.png"

displayURL="https://www.curseforge.com/minecraft/mc-mods/apotheosis"

[[mixins]]
config="apotheosis.mixins.json"

[[dependencies.apotheosis]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.187,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="placebo"
    type="required"
    versionRange="[9.9.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="apothic_attributes"
    type="required"
    versionRange="[2.7.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="apothic_spawners"
    type="required"
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="apothic_enchanting"
    type="required"
    versionRange="[1.5.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="curios"
    type="optional"
    versionRange="[9.5.1+1.21.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="gateways"
    type="optional"
    versionRange="[5.1.0,)"
    ordering="AFTER"
    side="BOTH"
